version: "3.5"

services:
  db:
    image: mariadb:10.9
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "./db:/var/lib/mysql"
      - "./mysql-init-files:/docker-entrypoint-initdb.d"
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_DATABASE_FILE=/run/secrets/mysql_db"
      - "MYSQL_USER_FILE=/run/secrets/mysql_user"
      - "MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password"
      - "MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password"
    restart: always
    secrets:
      - mysql_db
      - mysql_user
      - mysql_user_password
      - mysql_root_password

  app:
    image: kodcloud/kodbox:v1.3604
    ports:
      - 80:80
    links:
      - db
      - redis
    volumes:
      - "./site:/var/www/html"
    environment:
      - "MYSQL_SERVER=db"
      - "MYSQL_DATABASE_FILE=/run/secrets/mysql_db"
      - "MYSQL_USER_FILE=/run/secrets/mysql_user"
      - "MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password"
      - "CACHE_HOST=redis"
#      - "PUID=1050"
#      - "PGID=1051"
    restart: always
    secrets:
      - mysql_db
      - mysql_user
      - mysql_user_password

  redis:
    image: redis:alpine3.17
    environment:
      - "TZ=Asia/Shanghai"
    restart: always

secrets:
  mysql_db:
    file: "./mysql_db.txt"
  mysql_user:
    file: "./mysql_user.txt"
  mysql_user_password:
    file: "./mysql_user_password.txt"
  mysql_root_password:
    file: "./mysql_root_password.txt"
