version: '3.5'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always
    
  app:
    image: kodcloud/kodbox:v1.15-fpm-alpine
    volumes:
      - "./data:/var/www/html"
    restart: always

  web:
    image: nginx:alpine
    ports:
      - 80:80
    links:
      - db
      - redis
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./data:/var/www/html:ro"
    depends_on:
      - app
    restart: always
    
  redis:
    image: redis:alpine
    restart: always
