version: '3.5'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ"
      - "MYSQL_ROOT_PASSWORD="
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always
    
  app:
    image: kodcloud/kodbox
    ports:
      - 80:80
    links:
      - db
      - redis
    volumes:
      - "./kodbox:/var/www/html"
    restart: always

  redis:
    image: redis:alpine
    environment:
      - "TZ"
    restart: always
