version: '3.5'

services:
  db:
    image: registry.cn-hangzhou.aliyuncs.com/kodcloud/mariadb:10.5.9
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "./db:/var/lib/mysql"
      - "./mysql-init-files:/docker-entrypoint-initdb.d"
    environment:
      - "TZ"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always
    
  app:
    image: kodcloud/kodbox
    ports:
      - 80:80
    links:
      - db
      - redis
    volumes:
      - "./kodbox:/var/www/html"
    environment:
      - "MYSQL_SERVER"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
      - "SESSION_HOST"
    restart: always

  redis:
    image: registry.cn-hangzhou.aliyuncs.com/kodcloud/redis:alpine3.13
    environment:
      - "TZ"
    restart: always
